version: '3'

services:
  db:
    image: mysql
    restart: always
    container_name: movies_db
    ports:
      - 8880:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=moviesDB